### ISSUE TITLE
CT unable to find node from unique trail id

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/waves-intro#17]
Shows up in general repos as well
```
waves-intro : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/waves-intro/waves-intro_en.html?continuousTest=%7B%22test%22%3A%5B%22waves-intro%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589958265229%22%2C%22timestamp%22%3A1589962342551%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: unable to find node from unique Trail id
Error: Assertion failed: unable to find node from unique Trail id
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/assert/js/assert.js:22:13)
at Function.Trail.fromUniqueId (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/util/Trail.js:957:17)
at PDOMPointer.updateTrail (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/PDOMPointer.js:97:25)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/Input.js:1024:38)
at Input.focusinAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/Input.js:560:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/Input.js:733:30)
at Input.focusoutAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/Input.js:612:33)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/Input.js:733:30)
id: Bayes Chrome
Snapshot from 5/20/2020, 1:04:25 AM

----------------------------------

waves-intro : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/waves-intro/waves-intro_en.html?continuousTest=%7B%22test%22%3A%5B%22waves-intro%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589958265229%22%2C%22timestamp%22%3A1589967413692%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: unable to find node from unique Trail id
Error: Assertion failed: unable to find node from unique Trail id
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/assert/js/assert.js:22:13)
at Function.Trail.fromUniqueId (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/util/Trail.js:957:17)
at PDOMPointer.updateTrail (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/PDOMPointer.js:97:25)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/Input.js:1024:38)
at Input.focusinAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/Input.js:560:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/input/Input.js:733:30)
at KeyboardFuzzer.chooseNextElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/accessibility/KeyboardFuzzer.js:72:21)
at KeyboardFuzzer.fuzzBoardEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/scenery/js/accessibility/KeyboardFuzzer.js:161:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589958265229/joist/js/Sim.js:263:27
id: Bayes Chrome
Snapshot from 5/20/2020, 1:04:25 AM
```

**Comment by samreid** [comment]
It looks like this was corrected, thanks!  Closing.
